wandb:
  project: "neural-ray-predictor"
  name: "siren-integrated-pipeline"

dataset:
  path: "datasets/rays/my_dataset_01.pkl"
  max_rays: 20
  val_split_ratio: 0.001
  num_vis_samples: 4
  P_min: -120.0
  P_max: -40.0
  tau_min: 0.0
  tau_max: 0.000001

model:
  num_queries: 32 #48
  d_model: 256
  nhead: 8
  num_layers: 8
  omega_0_first: 30.0
  omega_0_hidden: 1.0

loss:
  alpha_fl: 0.25
  gamma_fl: 2.0
  lambda_alpha: 1.0
  lambda_tau: 1.0
  lambda_ang: 1.0 # 0.5
  aux_weights: [0.1, 0.2, 0.4] # [0.2, 0.4, 0.6]

eval:
  thresh_gain: 5.0
  thresh_delay: 5.0
  thresh_angle: 10.0
  p_threshold: 0.5
  line_len: 12.0
  aoa_is_propagation: True

train:
  epochs: 1000
  batch_size: 8
  lr: 0.0001
  lr_milestones: [100, 200]
  lr_gamma: 0.3

rf:
  rx_pattern:
    m: 4
    g_min: 1e-3
    front_only: true